.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE

Add pull request template and configure CODEOWNERS (temporarily only points to me but in the future we'll want to add other people as well)

Add pull request template and configure CODEOWNERS

---

apps/menu-bar/src/components/CircularProgress.tsx
apps/menu-bar/src/components/NativeColorPalette.tsx
apps/menu-bar/src/components/PathInput.tsx
apps/menu-bar/src/components/Text.tsx
apps/menu-bar/src/components/View.tsx
apps/menu-bar/src/hooks/useDeviceAudioPreferences.ts
apps/menu-bar/src/hooks/useListDevices.ts
apps/menu-bar/src/popover/Core.tsx
apps/menu-bar/src/utils/create-component-primitive.tsx
apps/menu-bar/src/utils/theme.ts
apps/menu-bar/src/windows/Onboarding.tsx
apps/menu-bar/src/windows/Settings.tsx
apps/menu-bar/src/windows/index.ts

To make Lint check passing and TS less angry.
Alter the code or suppress warning.
`yarn lint`: 12 issues -> 0 issues left
`yarn tsc`: 35 issues -> 12 issues left

fix lint issues and part of tsc warnings

---

CHANGELOG.md
apps/menu-bar/src/components/CommandCheckItem.tsx
apps/menu-bar/src/windows/Onboarding.tsx

Pre-flight checklist UI breaks whenever we show the reason the check failed 
This updates the Onboarding window to include a ScrollView in case the content does not fit the available space, updates the reason text to take 2 lines at most and adds an alert with the full details of what failed
https://github.com/expo/orbit/assets/11707729/92988ef9-46cc-4be0-b2d0-e7cd814c55f7

[menu-bar][cli] Fix Pre-flight checklist UI when a check fails

---

apps/menu-bar/.eslintignore
apps/menu-bar/codegen.ts
apps/menu-bar/package.json
apps/menu-bar/src/api/ApolloClient.ts
apps/menu-bar/src/generated/graphql.tsx
apps/menu-bar/src/generated/schema.graphql
apps/menu-bar/src/graphql/apps.gql
apps/menu-bar/src/popover/index.tsx
yarn.lock

Part 3 of a series of PRs to allow users to log in to their Expo accounts from Orbit
Closes ENG-9875
This PR add all the dependencies necessary to use Apollo client and graphql codegen and configures it to validate against our remote schema  
N / A

[menu-bar] Add apollo client and graphql codegen

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/WindowNavigator.m

Closes ENG-9871
Update WindowNavigator to check and update ActivationPolicy before opening/closing a window 
https://github.com/expo/orbit/assets/11707729/76ac9c74-eff5-4672-a8e0-bcaa5fce76ec

[menu-bar] Add support for showing dock icon while windows are opened

---

CHANGELOG.md
apps/menu-bar/src/components/ProjectIcon.tsx
apps/menu-bar/src/generated/graphql.tsx
apps/menu-bar/src/generated/schema.graphql
apps/menu-bar/src/graphql/apps.gql
apps/menu-bar/src/hooks/useGetPinnedApps.ts
apps/menu-bar/src/popover/Core.tsx
apps/menu-bar/src/popover/ProjectsSection.tsx

Closes ENG-9946
Get list of pinned apps from the new `pinnedApps` property

[menu-bar] Add pinned projects to Projects section

---

CHANGELOG.md
appcast.xml
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/macos/ExpoMenuBar-macOS/SparkleModule.h
apps/menu-bar/macos/ExpoMenuBar-macOS/SparkleModule.m
apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
apps/menu-bar/macos/Podfile
apps/menu-bar/macos/Podfile.lock
apps/menu-bar/src/components/Checkbox.tsx
apps/menu-bar/src/modules/SparkleModule.ts
apps/menu-bar/src/windows/Settings.tsx

Closes ENG-9715
- Add and configure Sparkle along with a new react-native module so we control automatic updates from the JS side
- Add "Check for updates automatically" checkbox to Settings window

[menu-bar] Add auto update support

---

CHANGELOG.md
apps/menu-bar/src/components/Avatar.tsx
apps/menu-bar/src/components/Button.tsx
apps/menu-bar/src/components/Image.tsx
apps/menu-bar/src/components/NativeColorPalette.tsx
apps/menu-bar/src/generated/graphql.tsx
apps/menu-bar/src/graphql/user.gql
apps/menu-bar/src/utils/helpers.ts
apps/menu-bar/src/windows/DebugMenu.tsx
apps/menu-bar/src/windows/Settings.tsx
apps/menu-bar/src/windows/index.ts

Closes ENG-9944
- Add Avatar and Image components
- Add Debug Menu Window 
- Improve the login UX
https://github.com/expo/orbit/assets/11707729/74ebbde2-f8a9-4fa8-b1dc-507eaf2de841

[menu-bar] Update the login UI

---

CHANGELOG.md
apps/cli/src/commands/InstallAndLaunchApp.ts
apps/cli/src/commands/ListDevices.ts
apps/cli/src/utils.ts
apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
apps/menu-bar/src/popover/Core.tsx
packages/eas-shared/src/env.ts
packages/eas-shared/src/index.ts

iOS devices connected via Wifi are not showing up on the menu-bar
Fix logic for filtering out duplicated Simulators 

[menu-bar] Fix listing iOS connected devices

---

CHANGELOG.md
apps/cli/src/commands/CheckTools.ts
apps/menu-bar/macos/ExpoMenuBar-macOS/WindowNavigator.h
apps/menu-bar/macos/ExpoMenuBar-macOS/WindowNavigator.m
apps/menu-bar/src/hooks/useWindowFocus.ts
apps/menu-bar/src/modules/WindowManager.ts
apps/menu-bar/src/providers/WindowProdiver.tsx
apps/menu-bar/src/windows/Onboarding.tsx
packages/common-types/src/cli-commands/checkTools.ts
packages/common-types/src/cli-commands/index.ts

Closes ENG-10481
- Add window focus detection
- Update `check-tools` command to run checks in parallel
- Update Onboarding to rerun checks when focusing the window
https://github.com/expo/orbit/assets/11707729/d315ab51-b626-40dd-818e-82165c4488cd

Update Onboarding to rerun checks when focusing the window

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/ProgressIndicatorView.m
apps/menu-bar/src/popover/Core.tsx
packages/common-types/src/InternalError.ts
packages/eas-shared/src/run/ios/appleDevice/AppleDevice.ts
packages/eas-shared/src/run/ios/appleDevice/installOnDeviceAsync.ts
packages/eas-shared/src/run/ios/appleDevice/protocol/LockdownProtocol.ts

When opening a tarball with multiple apps the prompt to choose which app should be launched was not being displayed 
Fix try{}catch  logic inside Core
https://github.com/expo/orbit/assets/11707729/7d0fafc4-1365-45e0-bd0f-4056e8374acf

[menu-bar] Fix opening tarballs with multiple app

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.h
apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.mm
apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
apps/menu-bar/src/modules/MenuBarModule.ts
apps/menu-bar/src/popover/ProjectsSection.tsx
apps/menu-bar/src/utils/constants.ts

Opening a URL url more causes the Popover not to be dismissed 
Add `closePopover` method to MenuBarModule 
https://github.com/expo/orbit/assets/11707729/d26fa629-cbc7-4834-9de7-2e4072f1373d

[menu-bar] Fix popover not closing when opening URLs

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

[menu-bar] Bump version to 1.0.1

---

CHANGELOG.md

Add missing chnagelog entry for #121 changes.
N/A

Update menu-bar app changelog

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 1.0.2 release

[menu-bar] Bump version to 1.0.2

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 1.0.3 release

[menu-bar] Bump version to 1.0.3

---

apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the 1.1.0 release

[menu-bar] Bump version to 1.1.0

---

CHANGELOG.md

Update changelog for the upcoming 1.0.4 release

Update changelog for the 1.0.4 release

---

CHANGELOG.md
apps/menu-bar/electron/src/main.ts
apps/menu-bar/src/modules/Storage.ts
apps/menu-bar/src/providers/DevicesProvider.tsx
apps/menu-bar/src/windows/Settings.tsx

We need to update the Settings UI to reflect the options available on Windows and Linux
Update Settings window UI

[menu-bar] Update Settings window UI

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist

Update changelog for the 1.1.0 release

Update changelog for the 1.1.0 release

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 1.1.1 release

[menu-bar] Bump version to 1.1.1

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
apps/menu-bar/macos/Podfile
apps/menu-bar/macos/Podfile.lock
yarn.lock

Follow up of https://github.com/expo/orbit/pull/203 now that https://github.com/facebook/react-native/issues/46213 has been resolved 
Reenable hermes in Podfile
Run MenuBar locally

[menu-bar] Reenable hermes

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 1.2.0 release

[menu-bar] Bump version to 1.2.0

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json
apps/menu-bar/src/components/DebugLogs/ObjectInspector.tsx
apps/menu-bar/src/components/NativeColorPalette.tsx
apps/menu-bar/src/windows/Settings.tsx

Bump versions for the upcoming 1.2.1 release

[menu-bar] Bump version to 1.2.1

---

.github/workflows/build.yml
CHANGELOG.md
apps/menu-bar/electron/forge.config.ts

Instead of manually building all these artifacts lets have a workflow to build this for us
Add build workflow for Linux and Windows
CI should be green

[github] Add build workflow for Linux and Windows

---

README.md

Update repo to align with https://expo.dev/orbit and highlight the multiplatform support of v2 release.
Drop macOS only references, add features highlight, other tweaks.
https://github.com/expo/orbit/tree/%40simek/readme-updates?tab=readme-ov-file#expo-orbit

[github] Update README.md to account for multiple platforms

---

CHANGELOG.md
apps/menu-bar/electron/package.json
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 2.0.2 release

[menu-bar] Bump version to 2.0.2

---

CHANGELOG.md
apps/menu-bar/electron/package.json
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 2.0.3 release

[menu-bar] Bump version to 2.0.3

---

CHANGELOG.md
apps/menu-bar/electron/src/TrayGenerator.ts
apps/menu-bar/electron/yarn.lock

Closes https://github.com/expo/orbit/issues/231
Update popover window position logic to use the current display based on the click bounds
Run locally on macos, linux and windows using multiple displays

[electron] Fix multi display popover position logic

---

CHANGELOG.md
apps/menu-bar/electron/package.json
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json

Bump versions for the upcoming 2.0.4 release

[menu-bar] Bump version to 2.0.4

---

CHANGELOG.md
apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
apps/menu-bar/metro.config.js
apps/menu-bar/package.json
yarn.lock

Building in release mode throws an error in Xcode 
- Fix build phase script when building in release mode
- Upgrade `react-native-svg-transformer` to 1.5.1
Archive the app in Xcode

[menu-bar][macos] Fix building in release mode

---

CHANGELOG.md
apps/menu-bar/src/popover/BuildsSection.tsx
apps/menu-bar/src/popover/Core.tsx
apps/menu-bar/src/utils/helpers.ts

Closes https://github.com/expo/orbit/issues/278
Add support launching multiple apps simultaneously
https://github.com/user-attachments/assets/bdbb1213-6eda-4846-a704-59bfd7511c28

[menu-bar] Add support launching multiple apps simultaneously

---

CHANGELOG.md
appcast.xml
apps/cli/src/commands/TrustedSources.ts
apps/menu-bar/electron/package.json
apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
apps/menu-bar/package.json
electron-updates.json

@gabrieldonadel/appcast

---

CHANGELOG.md

@gabrieldonadel/fix changelog
