expo/orbit

- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/device.ts
- apps/menu-bar/src/utils/helpers.ts
To allow the user to scroll through all available devices ensuring the footer is always displayed we should use a SectionList to display devices 
Update Devices list to use a SectionList and use `flexShrink:1`
https://github.com/expo/orbit/assets/11707729/a50b4074-a8a4-4d5f-89e6-8218a98fa199
> [menu-bar] Update Devices list to use a SectionList

- apps/cli/macos/entitlements.plist
- apps/cli/package.json
- apps/menu-bar/macos/AutoLauncher/AutoLauncherRelease.entitlements
- apps/menu-bar/macos/ExpoMenuBar-macOS/ExpoMenuBar-macOS.entitlements
- apps/menu-bar/macos/ExpoMenuBar-macOS/ExpoMenuBar-macOSRelease.entitlements
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
In order to avoid showing the "App cannot be opened because the developer cannot be verified" warning to users when running Orbit, we must notarize our app, which requires enabling Hardened Runtime capability 
<p align="center">
</p>
Enable Hardened runtime for ExpoMenuBar and AutoLauncher targets and add a `codesign` script to the cli in order to overwrite pkg's signature and enable Hardened runtime 
Archive and install the generated App on a different machine, ensuring the "App cannot be opened because the developer cannot be verified" warning would not be displayed when opening the app for the first time
> [menu-bar] Enable Hardened runtime for notarization

- apps/menu-bar/macos/AutoLauncher/AppDelegate.swift
The "Launch on login" functionality is broken 
Update `menuBarBundleID` value and update the code to use the more reliable `NSWorkspace.shared.urlForApplication` function to determine Orbit's path
1. Install Orbit
2. Enable "Launch on login"
3. Restart the computer
4. Check if Orbit is displayed on the menu bar
> [menu-bar] Fix AutoLauncher not opening Orbit on launch

- .gitignore
- apps/cli/package.json
- apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/package.json
To support both Apple Silicon e Intel Macs we must compile both versions of the CLI, one for arm64 and the other x64.
TODO:
Once we have an automated release process we can create individual apps releases for each platform and avoid shipping both CLIs
- Update the `archive` script to explicitly generate arm64 and x64 binaries
- Update native `runCli` method to check which CLI it should use
> [menu-bar] Add arm64 and x64 CLI versions to bundle

- apps/menu-bar/src/popover/Core.tsx
After header removal the build section was a bit too spaced out in comparision to the content below.
Adjust the builds section padding and static height.
> [menu-bar] spacing tweaks after header removal

- apps/cli/package.json
- apps/cli/tsconfig.build.json
Running `yarn build` inside the `cli` directory is not generating the build folder
Remove the unnecessary `tsconfig.build.json` file and just use the one tsconfig file for everything
Run `yarn build`
> [cli] Fix build script not outputting transpiled files

- CHANGELOG.md
- apps/cli/src/commands/ListDevices.ts
- apps/menu-bar/src/utils/device.ts
- packages/eas-shared/src/run/android/adb.ts
Closes https://github.com/expo/orbit/issues/23
Closes https://github.com/expo/orbit/issues/18
- Wrap CLI commands to list iOS and Android devices into `try{}catch`  so the `list-devices` command always returns an array even if the native commands fail
- Filter empty sections from Devices List
Configure a wrong "Custom Android SDK root location" and check if the devices list will show iOS devices 
Run `ANDROID_HOME=/Users/wrong/path yarn cli list-devices` and make sure CLI still outputs iOS devices
> [menu-bar][cli] Fix device list when Android SDK path is not configured correctly

- CHANGELOG.md
- apps/menu-bar/src/hooks/useSafeDisplayDimensions.ts
- apps/menu-bar/src/popover/Core.tsx
Closes https://github.com/expo/orbit/issues/22
It seems that there is a bug in `react-native-macos` when calling `Dimensions.get('screen')` right after unplugging a display and awaking the computer, which results in the Dimensions API returning `height: 0`
TODO
This PR adds a workaround that attempts to mitigate this problem by waiting 100ms and trying to get the screen dimensions again.
1. Open the Popover on a second monitor
2. Put your Mac to sleep from the second monitor
3. Unplug the monitor
4. Wake up your Mac and press the Orbit Icon on the menu bar
5. Ensure the devices list is displayed correctly
> [menu-bar] Fix Popover height after putting Mac to sleep

- CHANGELOG.md
- apps/menu-bar/src/components/Button.tsx
- apps/menu-bar/src/components/DeviceItem.tsx
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/windows/Onboarding.tsx
It was possible to click "Launch" button multiple time for a device, which lead to restarting the same emulator/simulator and delaying the actual launch.
After first press replace the button with launching label, await for boot command to finish, to hide label.
The changes have been tested by running Orbit app locally.
https://github.com/expo/orbit/assets/719641/78d2e60f-6930-4333-ad1a-5080582a31c9
> [menu-bar] prevent multiple "launch" clicks, add indicator when booting

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.m
Closes ENG-9713
Having a native context menu ensures that if, for any reason, the JS menu becomes unresponsive users can right click on the menu bar icon and close the app
Add a native NSMenu context menu
https://github.com/expo/orbit/assets/11707729/47157ec3-541b-42f2-850b-db1b8af13662
> [menu-bar] Add context menu

- CHANGELOG.md
- apps/menu-bar/src/popover/Core.tsx
To ensure we always keep the devices list up to date we should refetch the devices list after launching 
Add a refetch call after finishing launching a device
https://github.com/expo/orbit/assets/11707729/14947a1c-db7a-471e-9c73-b9d66465dbb4
> [menu-bar] Refetch devices list after launch

- CHANGELOG.md
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/popover/SectionHeader.tsx
Minor adjustments to the UI to improve the user experience
- Show an alert if there are no available devices when trying to launch a build from EAS
- Improve Popover height estimations
> [menu-bar] Add alert when trying to install build with no available devices

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
Intel Mac users are currently unable to list-devices and launch builds due to an incorrect string comparison to resolve the cli resource name 
Update `getCliResourceNameForArch` method to use `isEqualToString` 
Run Orbit in an x64 Intel machine and ensure communication between the menu-bar and cli is working as expected
> [menu-bar] Fix CLI resource name on x64

- apps/menu-bar/src/popover/Core.tsx
Remove no longer needed horizontal spacing for the "Builds" header after latest layout/wrapper changes.
Change has been reviewed by building and running Orbit locally.
> [menu-bar] remove no longer needed spacing from Builds header

- apps/menu-bar/macos/ExpoMenuBar-macOS/WebAuthenticationSession.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/WebAuthenticationSession.m
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/src/modules/WebAuthenticationSessionModule.ts
Part 1 of a series of PRs to allow users to log in to their Expo accounts from Orbit
Closes ENG-9875
This introduces a new `WebAuthenticationSession` native module that uses `ASWebAuthenticationSession` to do the OAuth flow in the same way Expo Go and dev-client authenticate on iOS 
https://github.com/expo/orbit/assets/11707729/5115fed8-b1cc-4a6b-9542-6f0767f9d31a
> [menu-bar] Add WebAuthenticationSession module

- apps/menu-bar/index.js
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/macos/Podfile.lock
- apps/menu-bar/package.json
- apps/menu-bar/src/api/Config.ts
- apps/menu-bar/src/modules/Storage.ts
- apps/menu-bar/src/windows/Settings.tsx
- yarn.lock
Part 2 of a series of PRs to allow users to log in to their Expo accounts from Orbit
Closes ENG-9875
This PR Adds a login/logout button to the settings window and also adds `react-native-mmkv` and `react-native-url-polyfill` as dependencies 
The AsyncStorage migration will be addressed in a future PR  
https://github.com/expo/orbit/assets/11707729/ee066321-a748-45d0-aa02-7b737d808eac
> [menu-bar] Add Login button to settings window

- apps/menu-bar/macos/ExpoMenuBar-macOS/FilePicker.m
- apps/menu-bar/src/modules/FilePickerModule.ts
Close ENG-9947
Add a new parameter to `pickFileWithFilenameExtension` so we can show the "Select"/"Install" text in the NSOpenPanel button
> [menu-bar] Add custom prompt support to FilePicker module

- apps/menu-bar/macos/ExpoMenuBar-macOS/WindowNavigator.m
- apps/menu-bar/src/windows/index.ts
Closes ENG-9954
Instead of directly reading width and height from `[window frame]` we should use `contentRectForFrameRect` in order to get the actual height of the windows (without including the title bar) and prevent always resizing 
https://github.com/expo/orbit/assets/11707729/9fa241d7-1459-44b6-8612-588d4d8e4d53
> [menu-bar] Fix WindowNavigator size calculations when showing an existing window

- .github/workflows/lint-and-tsc.yml
- CHANGELOG.md
To help us remember to always keep the changelog file up to date we should add an action that checks all PRs for changes on CHANGELOG.md
This PR uses the [changelog-enforcer](https://github.com/dangoslen/changelog-enforcer) action to enforce that every pull request in this repo includes a change to the changelog file. When necessary this check can be skipped by adding the `skip-changelog-check` label to the PR
Don't change the changelog and check if the action fails
> [github] Add check for missing changelogs

- CHANGELOG.md
- apps/menu-bar/macos/AutoLauncher/AppDelegate.swift
Closes ENG-9963
The AutoLauncher process should be terminated after successfully launching Orbit otherwise users will see the AutoLauncher process in their Action Monitor running all the time, even after closing Orbit, which sounds dodgy.
Build using the AutoLauncher scheme and ensure Orbit is launched and the AutoLauncher process is terminated
https://github.com/expo/orbit/assets/11707729/bfbb6a39-42a4-4bc4-a243-712d55427919
> [menu-bar] Terminate Auto Launcher after launching main Orbit application

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/ExpoMenuBar-macOS-Bridging-Header.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/SwifterWrapper.swift
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/macos/Podfile
- apps/menu-bar/macos/Podfile.lock
Closes ENG-9945
This will allow us to remove the need for an "Enable Orbit" option inside User Settings, given that we can just fetch the local server from the website and verify if Orbit is running. As long as Orbit is open, the "Open with Orbit" button will be displayed. 
One other advantage of having a local HTTP server is the ability to check the version that is installed in the user's computer and potentially show different options, this could be necessary in the future when we add new features to Orbit. 
This PR adds `Swifter` as a CocoaPods dependency, providing us a tiny and versatile HTTP server engine.
The set of possible ports used for this are 35783, 47909, 44171, and 50799, and were chosen randomly. All ports are unassigned and are not used by any largely known applications. …
> [menu-bar] Add local HTTP server to circumvent deep-link limitations

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/SwifterWrapper.swift
Closes ENG-9945
Follow up of #52
Unfortunately, the most recent version of [Swifter](https://github.com/httpswift/swifter), v1.5.0, does not yet support custom headers when using the default `.ok` `HttpResponse`, because of that we need to use the `.raw` response in order to pass the custom `Access-Control-Allow-Origin` header. This PR also adds `exp.host` (used by Snack) to the list of allowed domains 
Tested fetching the local server from the website
> [menu-bar] Add CORS headers to local HTTP server

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/SwifterWrapper.swift
Closes ENG-9945
Properly parse query params by removing the percent-encoding before checking the root domain of the URL
Fetch the `orbit/open` from the website and ensure everything is working as expected
> [menu-bar] Fix local server query params decoding

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/SwifterWrapper.swift
Closes ENG-9945
Properly decode and replace URL protocol when  using `exp://` protocol 
Fetch the `orbit/open` from the website and ensure everything is working as expected
> [menu-bar] Fix local server deeplink

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/FileHandler.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/FileHandler.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/FileHandlerManager.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/FileHandlerManager.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/Info.plist
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/src/modules/FileHandlerModule.ts
- apps/menu-bar/src/popover/Core.tsx
Closes ENG-10029
- Update Info.plist to include document type definitions for APKs, IPAs and tar.gz files and added a new FileHandler module to dispatch the openFile event to the JS side 
- Refactor Core component logic to download and install apps
https://github.com/expo/orbit/assets/11707729/6ce60441-caae-44bc-9805-45fcb6c0febe
> [menu-bar] Add support for installing apps from Finder

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/DragDropStatusItemView.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/DragDropStatusItemView.m
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
Closes ENG-10049
Add drag and drop support to the menu bar icon by implementing a custom NSView class with `registerForDraggedTypes` and the associated functions. Currently we only support files using the following extensions: `apk`, `ipa`, `app` and `gz`
https://github.com/expo/orbit/assets/11707729/6e4862dd-57b7-4473-9c98-4b09c795dd15
> [menu-bar] Add drag and drop support to menu bar icon 

- CHANGELOG.md
- packages/eas-shared/package.json
- packages/eas-shared/src/log.ts
- yarn.lock
Close ENG-10132
When copying part of the code from `eas-cli` and `expo-cli` we ended up adding some unnecessary dependencies
Remove unnecessary dependencies
build `eas-shared` and `cli` and run menu-bar locally
> [eas-shared] Remove unnecessary dependencies

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
Closes ENG-10052
To improve the performance of the `runCommand` method, this PR introduces the following optimizations:
-  Remove `[task waitUntilExit]`, which blocks the main thread until the task is completed and use `setReadabilityHandler` and `setTerminationHandler`instead of relying on NSNotificationCenter for updates to allow asynchronous execution.
- Move the NSTask execution and reading of output to a background queue
- Use NSMutableString to avoid String concatenation on every update
Use Xcode Instruments to profile CPU usage
Before
After
> [menu-bar] Improve performance when running cli commands

- CHANGELOG.md
- package.json
- patches/react-native-svg+13.9.0.patch
- yarn.lock
macOS Sonoma will be officially released on September 26 and with it comes a breaking change to `drawRect`, you can no longer trust that the OS will provide you a dirtyRect that will be within the bounds of your view. Specifically (from the appkit release notes):
> Filling the dirty rect of a view inside of -drawRect. A fairly common pattern is to simply rect fill the dirty rect passed into an override of NSView.draw(). The dirty rect can now extend outside of your view’s bounds. This pattern can be adjusted by filling the bounds instead of the dirty rect, or by setting clipsToBounds = true.
This causes libraries like `react-native-svg` that rely on `drawRect` to take up the full width/height of your window.
Closes ENG-10149
Closes #30
Patch react-native-svg `RNSVGSvgView` while …
> [menu-bar] Patch react-native-svg to support macOS Sonoma

- CHANGELOG.md
- apps/cli/src/commands/BootDevice.ts
- apps/cli/src/commands/ListDevices.ts
- apps/cli/tsconfig.json
- apps/menu-bar/src/commands/listDevicesAsync.ts
- apps/menu-bar/src/components/DeviceItem.tsx
- apps/menu-bar/src/hooks/useListDevices.ts
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/device.ts
- apps/menu-bar/tsconfig.json
- common-types/src/devices.d.ts
- common-types/tsconfig.json
- packages/eas-shared/src/index.ts
- packages/eas-shared/src/run/android/adb.ts
- packages/eas-shared/src/run/android/emulator.ts
- packages/eas-shared/src/run/index.ts
- packages/eas-shared/src/run/ios/appleDevice/AppleDevice.ts
- packages/eas-shared/src/run/ios/device.ts
- packages/eas-shared/src/run/ios/simulator.ts
- packages/eas-shared/tsconfig.json
To ensure that the communication between the menu-bar and CLI is accurate we should share common types between projects 
Move device types to a new `common-types` folder at the root level of the repo and decouple `AndroidDevice` in `AndroidConnectedDevice` and `AndroidEmulator` 
Run menu-bar and cli and ensure TS and lint tests are green
> [menu-bar][cli] Extract device types in a common file

- CHANGELOG.md
- CONTRIBUTING.md
- apps/cli/package.json
- apps/cli/src/index.ts
- apps/cli/src/utils.ts
- apps/menu-bar/macos/ExpoMenuBar-macOS/FilePicker.m
- apps/menu-bar/src/modules/FilePickerModule.ts
- apps/menu-bar/src/popover/Core.tsx
- packages/eas-shared/src/run/ios/simctl.ts
- packages/eas-shared/src/run/ios/xcrun.ts
- Could not build on my desktop because I run Node 20
- CLI would not work correctly without fixes in `simctl.ts` and `xcrun.ts`
- File picker in menu bar would not work without adding `await` and removing file extensions
- Fixed the issues
- Added some steps in `CONTRIBUTING.md`
- Existing CI should pass
> Fix some build and running issues

- CHANGELOG.md
- CONTRIBUTING.md
- apps/cli/package.json
- apps/menu-bar/package.json
- lerna.json
- package.json
- packages/eas-shared/package.json
- yarn.lock
The current setup for running Orbit locally requires the user to take multiple steps and can be complex for newcomers.
- Add Lerna  
- Update CONTRIBUTING.md
run `yarn` `build`, `watch` and `typecheck` at the root folder level and make sure everything works as expected
> [workspaces] Add lerna

- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/FilePicker.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
- apps/menu-bar/src/modules/MenuBarModule.ts
- apps/menu-bar/src/popover/Core.tsx
The `pickFileWithFilenameExtension` change introduced by https://github.com/expo/orbit/pull/69 ended up breaking support for apk files
Use both `UTType typesWithTag` and  `UTType typeWithFilenameExtension` methods to find `UTType`s
https://github.com/expo/orbit/assets/11707729/f6b6bfe9-20bb-482b-aca8-4393b994825d
> [menu-bar] Fix opening local APK files

- CHANGELOG.md
- apps/cli/src/commands/InstallAndLaunchApp.ts
- apps/menu-bar/src/popover/Core.tsx
- packages/common-types/src/InternalError.ts
- packages/eas-shared/src/run/ios/appleDevice/AppleDevice.ts
- packages/eas-shared/src/run/ios/appleDevice/installOnDeviceAsync.ts
- packages/eas-shared/src/run/ios/device.ts
- packages/eas-shared/src/run/ios/xcrun.ts
We should allow users to install iOS apps signed with ad hoc or enterprise provisioning profiles
Add support for iOS internal distribution apps
Run menu-bar locally and install an iOS app signed using an ad-hoc provisioning profile
> [menu-bar][cli] Add support for iOS internal distribution apps

- CHANGELOG.md
- apps/menu-bar/.prettierrc.js
- apps/menu-bar/src/hooks/useListDevices.ts
- apps/menu-bar/src/modules/Storage.ts
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/device.ts
- apps/menu-bar/src/windows/Settings.tsx
- packages/common-types/src/devices.ts
- packages/eas-shared/src/run/ios/simulator.ts
- Allow Orbit user to only show certain simulators/emulators (e.g. only iOS or only Android)
- Allow Orbit user to run Apple TV builds on Apple TV simulators (new experimental feature) 
- New user pref "Show experimental features" (false by default)
- New user prefs to hide/show different simulator types
- Checkbox in settings UI for the experimental features
- New row in menu bar UI to switch between different simulator lists
- Awareness of `osType=tvOS` in `common-types` and `eas-shared`
- Other changes:
- Boolean user preferences are now always defined -- defaults in `Storage.ts`
- Allow showing debug menu even if we are not logged in
- Tested on desktop
> Changes for TV support

- CHANGELOG.md
- apps/menu-bar/src/hooks/useGetPinnedApps.ts
- apps/menu-bar/src/hooks/usePopoverFocus.ts
- apps/menu-bar/src/hooks/useSafeDisplayDimensions.ts
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/popover/ProjectsSection.tsx
The user should always see the most recent data regarding pinned projects
Refetch pinned apps when focusing the menu bar 
> [menu-bar] Refetch pinned apps on menu bar focus

- CHANGELOG.md
- apps/menu-bar/src/components/PathInput.tsx
- apps/menu-bar/src/components/View.tsx
- apps/menu-bar/src/hooks/useListDevices.ts
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/theme.ts
- apps/menu-bar/src/windows/Settings.tsx
- apps/menu-bar/src/windows/index.ts
Closes ENG-10385
This PR moves the Platform filtering feature to Settings window and updates the `useListDevices` to no longer requite a reload after toggling platforms
> [menu-bar] Improve Platform filtering UI

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/SystemIconViewManager.m
- apps/menu-bar/src/components/SystemIconView.tsx
Closes ENG-10386
Refactor SystemIconView to no longer inherit from RCTImageView and use NSImageView directly. This way we can easily set the image as a template and change the view contentTintColor
https://github.com/expo/orbit/assets/11707729/6d8b23e6-59b1-4b04-9694-c459509b0076
> [menu-bar] Refactor SystemIconView to work when switching themes

- CHANGELOG.md
- apps/menu-bar/src/hooks/useDeviceAudioPreferences.ts
- apps/menu-bar/src/hooks/useListDevices.ts
- apps/menu-bar/src/modules/Storage.ts
- apps/menu-bar/src/popover/BuildsSection.tsx
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/helpers.ts
- packages/eas-shared/src/run/ios/appleDevice/AppleDevice.ts
- packages/eas-shared/src/run/ios/appleDevice/client/InstallationProxyClient.ts
Closes ENG-10390
- Extract builds section into a component
- Added status specific to Snack
- Fix rerendering issue related to userPreferences 
> [menu-bar] Improve UI feedback when opening a snack project

- CHANGELOG.md
- apps/menu-bar/src/modules/Storage.ts
When migrating from  v0.1.3 to latest default user preferences are not applied, causing the user to see no simulators/emulators in the menu bar 
Update `getUserPreferences` to merge the retrieved object from mmkv with the default preferences, this ensures that in case we add new keys to `UserPreferences` `getUserPreferences` will always return the whole object with the default values
1. Reset local storage
2. install Orbit v0.1.3 
3. Open the Settings Window and change some configuration (e.g. `Run Android emulator without audio`)
4. Install orbit from main
5. Check if ios and android platforms are enabled
> [menu-bar] Fix user default preferences storage migration

- CHANGELOG.md
- apps/menu-bar/src/hooks/useListDevices.ts
- apps/menu-bar/src/modules/Storage.ts
- apps/menu-bar/src/windows/Settings.tsx
Instead of having a dedicated check check box for just one experimental feature, we can just show "experimental" next to the the tvOS label
Remove the experimental features option from Settings
> [menu-bar] Remove experimental features option from Settings

- CHANGELOG.md
- apps/cli/src/commands/DownloadBuild.ts
- apps/cli/src/commands/LaunchSnack.ts
- apps/menu-bar/src/hooks/useListDevices.ts
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/device.ts
- packages/common-types/src/InternalError.ts
- packages/common-types/src/cli-commands/index.ts
- packages/common-types/src/cli-commands/listDevices.ts
- packages/common-types/src/index.ts
- packages/eas-shared/src/download.ts
- packages/eas-shared/src/run/ios/appleDevice/AppleDevice.ts
- packages/eas-shared/src/run/ios/appleDevice/ClientManager.ts
- packages/eas-shared/src/run/ios/constants.ts
- packages/eas-shared/src/run/ios/device.ts
- packages/eas-shared/src/run/ios/simulator.ts
Users should be able to launch Snack projects on real iOS devices just like on simulators 
Apple does not allow us to directly install Expo Go (without doing proper app distribution) on the user's device but using `devicectl` we can check if the app is installed and if not, open the Expo Go screen inside App Store app on the device.  `devicectl` also allow us to pass URL payloads to real devices in a similar way to `simctl openurl`
run menu-bar locally and launch snack projects on a real iOS device
> Add support for opening snack projects on real iOS devices

- CHANGELOG.md
- apps/menu-bar/macos/Podfile.lock
- apps/menu-bar/package.json
- patches/@react-native-clipboard+clipboard+1.12.1.patch
- yarn.lock
There should be no warnings when running menu-bar locally 
Update @react-native-clipboard/clipboard to the latest version and patch `new NativeEventEmitter() was called with a non-null argument ` warnings based on https://github.com/react-native-clipboard/clipboard/pull/207
Run menu-bar locally and ensure that using `useClipboard` does not throw any warnings
> [menu-bar] Upgrade @react-native-clipboard/clipboard to 1.12.1 and patch warnings

- CHANGELOG.md
- apps/menu-bar/src/hooks/useDeepLinking.ts
If a user opens Orbit through a deep link the initialURL callback gets invoked multiple times
Fix useDeepLinking hook initial URL
Open Orbit through a deep link and ensure the deeplink is only handled once
> [menu-bar] Fix useDeepLinking hook initial URL

- CHANGELOG.md
- apps/menu-bar/src/popover/Core.tsx
Closes https://github.com/expo/orbit/issues/107
Instead of immediately trying to get the selected device when launching a build from EAS, first download the app and then check for the list of available devices, that way we can avoid a race condition while the list of devices is loaded 
Launch a build from EAS with the app closed
> [menu-bar] Fix installing app from cold start

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.mm
- apps/menu-bar/src/App.tsx
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/popover/index.tsx
- apps/menu-bar/src/providers/DevicesProvider.tsx
Closes https://github.com/expo/orbit/issues/105
-  Refactor `useListDevices` hook to use React Context, allowing us to detect from different parts of the app that the initial list of devices has been loaded 
- Automatically open popover when the user opens the app or reopens it from the Dock or Spotlight
> [menu-bar] Automatically open popover when the user tries to reopen the app from the Dock or Spotlight

- CHANGELOG.md
- apps/menu-bar/src/components/CommandCheckItem.tsx
- apps/menu-bar/src/windows/Onboarding.tsx
Command check component on Onboarding window is not showing the loading status 
https://github.com/expo/orbit/assets/11707729/988c4053-7338-4f17-8e05-9d73b99ef675
Add loading prop to CommandCheckItem component
Run menu bar locally and go through onboarding
https://github.com/expo/orbit/assets/11707729/10b3f1f0-abce-4dc2-b96e-bf8535da5903
> [menu-bar] Fix command check loading status

- apps/menu-bar/.eas/build/configureMacOSCredentials/README.md
Old links lead to 404.
Update used docs links.
No 404 anymore.
> [menu-bar] correct links in GHA credentials function

- CHANGELOG.md
- apps/cli/src/commands/LaunchSnack.ts
- packages/eas-shared/src/run/android/emulator.ts
- packages/eas-shared/src/run/ios/simulator.ts
Closes ENG-10972
Improve Snack support for older SDKs on iOS and Android
on iOS Simulators:
- Check if Expo Go is installed and attempt to read compatible SDK versions from `EXSDKVersions.plist` 
on iOS Real devices:
- Only check if Expo Go is installed, we can't really do much given that we don't have access to  `EXSDKVersions.plist` (even through HouseArrest) and we can't install specific versions of Expo Go
on Android:
- We don't have a file equivalent to `EXSDKVersions.plist` on Android so we need to rely on checking the app version against the latest expo go release for a given SDK, reading from API V2 versions/latest. If the opened Snack requires a downgrade of Expo Go, first uninstall the app to avoid `INSTALL_FAILED_VERSION_DOWNGRADE` …
> [cli] Improve Snack support for older SDKs

- CHANGELOG.md
- packages/eas-shared/src/run/android/emulator.ts
Installing apps on Android real devices gives the following error
Check the device type before trying to activate the emulator window
Tested installing an apk in a real device
> [cli] Fix installing apps on Android real devices

- .github/workflows/lint-and-tsc.yml
Fix changelog warning check step, GHA core actions bumps.
There is no warning in changelog step output.
> [github] bump workflow actions

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.mm
Closes ENG-11012
Provide the appropriate options to `windowNavigator openWindow`
https://github.com/expo/orbit/assets/11707729/c929da5b-e59f-4647-98f1-333cea3fcd8e
> [menu-bar] Fix Settings window size when opening it from the context menu

- CHANGELOG.md
- apps/menu-bar/babel.config.js
- apps/menu-bar/macos/ExpoMenuBar-macOS/ProgressIndicatorManager.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/ProgressIndicatorView.m
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/macos/Podfile
- apps/menu-bar/macos/Podfile.lock
- apps/menu-bar/package.json
- apps/menu-bar/tsconfig.json
- yarn.lock
Closes ENG-10992
Upgrade react-native and react-native-macos to 0.73.1 based on https://react-native-community.github.io/upgrade-helper/?from=0.72.1&to=0.73.1&package=react-native-macos
Also had to change `UIActivityIndicatorViewStyleWhiteLarge` and `UIActivityIndicatorViewStyleWhite` to `UIActivityIndicatorViewStyleLarge` as both variables have been deprecated on newer versions of macos
We can't upgrade react-native-macos to 0.73.2 yet because it causes an issue with Hermes where it can't find the appropriate tarball and tries to build from source (which does not work), I'll send a PR to react-native-macos later today to fix it
Run menu-bar on debug and release mode
> [menu-bar] Upgrade react-native to 0.73.1

- CHANGELOG.md
- packages/eas-shared/src/run/ios/simulator.ts
In some very specific cases, the user may encounter an error stating that `osascript is not allowed assistive access. (-1719)` when trying to launch a build in the simulator. This only happened once to me, I tried to reproduce this in different machines and  unfortunately couldn't find reproducible steps
Add a try-catch block around the osascript call given that we can safely ignore this error and just continue with the launch of the app
Run the app locally and launch a simulator build from the website
> [eas-shared] Ignore osascript error when launching on Simulator

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.mm
- apps/menu-bar/macos/ExpoMenuBar-macOS/AutoResizerRootView.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
- apps/menu-bar/src/hooks/usePopoverFocus.ts
- apps/menu-bar/src/hooks/useSafeDisplayDimensions.ts
- apps/menu-bar/src/modules/MenuBarModule.ts
- apps/menu-bar/src/popover/Core.tsx
We always had issues with resizing the Popover height accurately, but after upgrading react-native-macos to 0.73 this has become more apparent, often cropping the "Quit" button on the UI  
In react-native-macos to 0.73 `Dimensions.get('screen')` no longer returns the actual screen size on the first few renders (https://github.com/microsoft/react-native-macos/commit/d1ed53d49176e1621facd65c89c53be30da65f3c), so instead of relying on multiple retries this PR refactor `useSafeDisplayDimensions` to not use the Dimensions API.
By exporting the initial screen size as a constant in MenuBarModule and including the screen size in the body of the `popoverFocused` event we can ensure that the screen size data is always up to date.
1. Open the Popover on a second monitor
2. Put your Mac to sleep from …
> [menu-bar] Improve popover height calculations when using multiple displays

- apps/cli/package.json
- apps/cli/src/mmkv.ts
- apps/menu-bar/macos/ExpoMenuBar-macOS/MenuBarModule.m
- apps/menu-bar/src/modules/MenuBarModule.ts
- apps/menu-bar/src/modules/Storage.ts
- packages/common-types/src/index.ts
- packages/common-types/src/storage.ts
- yarn.lock
Fetching specific data from an Expo update requires the request to be authenticated, and given that this logic will be handled by the CLI we need to add support for sharing auth credentials between the cli and the menu-bar
Related to https://github.com/expo/orbit/pull/134
- Add nodejs-mmkv dependency to access the same MMKV instance used by the menu-bar  
- Add `homedir` constant to `MenuBarModule`
- Move MMKV path to the same folder as other expo apps (e.g. expo-cli and eas-cli)
- Run menu-bar and ensure all data is being migrated correctly 
- Run cli and read session secret using getSessionSecret
> [cli] Read auth credentials from menu-bar MMKV storage

- apps/cli/codegen.ts
- apps/cli/package.json
- apps/cli/src/api/GraphqlClient.ts
- apps/cli/src/graphql/builds.gql
- apps/cli/src/graphql/generated/graphql.ts
- apps/cli/src/mmkv.ts
- apps/menu-bar/src/api/ApolloClient.tsx
- apps/menu-bar/src/windows/Settings.tsx
- packages/common-types/src/constants.ts
- packages/common-types/src/index.ts
- yarn.lock
In order to read specific information from an update we need to interact with our graphql API from the CLI 
- Add `graphql-request` and `@graphql-codegen`
- Configure a GraphQLClient using `graphql-request`
- Add an example query
```
await graphqlSdk.getAppBuildForUpdate({
appId: manifest.extra?.eas?.projectId ?? '',
platform,
distribution,
});
```
> [cli] Add graphql-request and graphql codegen

- CHANGELOG.md
- apps/menu-bar/macos/Podfile.lock
- apps/menu-bar/modules/file-picker/expo-module.config.json
- apps/menu-bar/modules/menu-bar/expo-module.config.json
- apps/menu-bar/package.json
- yarn.lock
SDK 50 is out!
- `yarn add expo@50.0.2` and `npx expo install --fix`
- update expo-module config files to use "apple" platform instead of "ios" (https://github.com/expo/expo/pull/26398)
> [menu-bar] Upgrade to Expo SDK 50

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/SwifterWrapper.swift
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/utils/parseUrl.ts
Follow up of https://github.com/expo/orbit/pull/134
- Update the local server to parse deep links that include routes (e.g. /update, /snack, /download) 
- Update `identifyAndParseDeeplinkURL` to be handle unsupported routes that we may add in future versions  
Send a GET request to `http://127.0.0.1:35783/orbit/open?url=expo-orbit://update/staging-u.expo.dev/update/aa4316ea-2dae-47c4-9405-49c7ceeefb5d?platform=android`
> [menu-bar] Add support for launching updates from local server

- apps/cli/macos/entitlements.plist
- apps/cli/pkg.config.json
`nodejs-mmkv` broke CLI when codesigning
Update pkg config to only include *.node files from `nodejs-mmkv`, reducing the final bundle size and update cli entitlements to disable library validation
1. yarn archive 
2. yarn codesign
3. ./orbit-cli-arm64
> [cli] Fix codesigning

- CHANGELOG.md
- apps/cli/src/commands/LaunchUpdate.ts
- apps/menu-bar/src/popover/Core.tsx
- packages/common-types/src/InternalError.ts
`launchUpdateAsync` errors are getting silently dismissed 
Update catch condition to also alert messages from Error instances 
>   [menu-bar] Fix launchUpdateAsync errors not being displayed

- CHANGELOG.md
- apps/cli/package.json
- apps/cli/src/commands/LaunchSnack.ts
- yarn.lock
Snack is moving onto EAS Updates for SDK 50. This adds support to the newer URL format, using `snack-content` helpers.
- Added `snack-content@2.0.0-preview.1`
- Updated logic to try `parseRuntimeUrl` before falling back to legacy code
Open a snack from https://staging-snack.expo.dev
> [snack][cli] Add support for EAS Update Snack Runtime URLs

- apps/cli/package.json
- apps/cli/src/mmkv.ts
- ts-declarations/nodejs-mmkv/index.d.ts
- yarn.lock
A new version of nodejs-mmkv was just released adding the ability to configure the log level 
Upgrade nodejs-mmkv to 0.2.0 and set log level to warning when running from the menubar
`EXPO_MENU_BAR=1 dist/orbit-cli-arm64 list-devices`
> Upgrade nodejs-mmkv to 0.2.0 and disable info logs

- CHANGELOG.md
- apps/menu-bar/metro.config.js
- apps/menu-bar/package.json
We should Expo CLI for all platforms
Update metro.config.js to resolve `react-native` imports to `react-native-macos` when building for macos
Run menu-bar for macos and web
> [menu-bar] Update metro config to support Expo CLI

- CHANGELOG.md
- packages/eas-shared/src/download.ts
In some cases, users might launch the same build multiple times through Orbit and there is not need to redownload the build file everytime 
Update the download function to cache build downloads by default 
Run `yarn cli download-build https://expo.dev/artifacts/eas/5QUw5J97RyQod9fxvGad5a.apk`
> [cli] Update download function to cache builds

- apps/cli/codegen.ts
- apps/cli/src/api/GraphqlClient.ts
- apps/menu-bar/codegen.ts
- apps/menu-bar/src/api/ApolloClient.tsx
- packages/common-types/src/constants.ts
We shouldn't use `https://exp.host/` anymore 
Update API URL and graphql endpoints to use api.expo.dev
Run `yarn gql`
> [common-types] Update api url and graphql endpoints

- CHANGELOG.md
- apps/menu-bar/electron/modules/AutoResizerRootViewManager/main.ts
- apps/menu-bar/electron/modules/mainRegistry.ts
- apps/menu-bar/modules/menu-bar/electron/preload.ts
- apps/menu-bar/src/components/AutoResizerRootView/index.web.tsx
- apps/menu-bar/tsconfig.json
Closes ENG-11331
- Implement electron version of AutoResizerRootView using ResizeObserver
- Update tsconfig to automatically include web types like `window` and `ResizeObserver`
Windows
macOS
> [menu-bar] Add electron support for AutoResizerRootView

- CHANGELOG.md
- apps/menu-bar/modules/menu-bar/index.ts
- apps/menu-bar/modules/menu-bar/ios/MenuBarExceptions.swift
- apps/menu-bar/modules/menu-bar/ios/MenuBarModule.swift
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/popover/DevicesListError.tsx
- apps/menu-bar/src/windows/Onboarding.tsx
When fatal errors happen on the CLI, the user gets no visual feedback that something went wrong, causing confusion and reports like this one https://github.com/expo/orbit/issues/18#issuecomment-1926576880 
Improve fatal CLI error handling by handling fatal errors on Onboarding and the main Popover
> [menu-bar] Improve fatal CLI error handling

- CHANGELOG.md
- apps/menu-bar/modules/menu-bar/index.ts
A regression of https://github.com/expo/orbit/pull/163 is causing CLI errors not to be converted correctly 
Update MenuBar error catching if statement to not ignore `CodedError`s
Manually trigger a CLI error return
> [cli] Fix cli errors not being converted

- CHANGELOG.md
- apps/cli/package.json
- apps/cli/src/commands/LaunchSnack.ts
- yarn.lock
Simple bump, this is the version that's going to production today.
- Updated `snack-content` version and implementation
See CI
> refactor: upgrade to `snack-content@2.0.0` preview 2

- CHANGELOG.md
- apps/menu-bar/electron/modules/mainRegistry.ts
- apps/menu-bar/electron/modules/preloadRegistry.ts
- apps/menu-bar/macos/Podfile.lock
- apps/menu-bar/modules/rudder/electron/main.ts
- apps/menu-bar/modules/rudder/electron/preload.ts
- apps/menu-bar/modules/rudder/expo-module.config.json
- apps/menu-bar/modules/rudder/index.ts
- apps/menu-bar/modules/rudder/ios/RNRudder.podspec
- apps/menu-bar/modules/rudder/ios/RudderModule.swift
- apps/menu-bar/modules/rudder/src/Rudder.types.ts
- apps/menu-bar/modules/rudder/src/RudderModule.ts
- apps/menu-bar/modules/rudder/src/RudderModule.web.ts
- apps/menu-bar/package.json
- apps/menu-bar/src/App.tsx
- apps/menu-bar/src/analytics/index.ts
- apps/menu-bar/src/popover/BuildsSection.tsx
- apps/menu-bar/src/popover/Core.tsx
- yarn.lock
Closes ENG-11324
- Create a RudderStack module using the macOS SDK for macOS and the JavaScript SDK for Electron. We can use the JavaScript SDK on both platforms because the JS SDK relies on window events that are not available in react-native
- Track App opened, application launched and deeplink events 
Run the menu-bar locally and make sure events are being logged
> [menu-bar] Add basic telemetry

- CHANGELOG.md
- apps/menu-bar/global.css
- apps/menu-bar/src/components/AutoResizerRootView/index.web.tsx
- apps/menu-bar/src/components/NativeColorPalette.tsx
- apps/menu-bar/src/components/PathInput.tsx
- apps/menu-bar/src/components/Text.tsx
- apps/menu-bar/src/modules/PlatformColor/index.web.ts
- apps/menu-bar/src/utils/theme.ts
Close ENG-11333
- Add global styles to react-native-web mimicking macOS Semantic Colors
- Add PlatformColor support for electron by converting semantic color strings into CSS variable values 
<table>
<tr>
<th>Light</th>
<th>Dark</th>
</tr>
<tr>
<td><img width="302" alt="Screenshot 2024-02-09 at 14 54 33" src="https://github.com/expo/orbit/assets/11707729/a7feffef-209d-4111-9e6c-c534dfdc9899"></td>
<td><img width="302" alt="Screenshot 2024-02-09 at 14 54 44" src="https://github.com/expo/orbit/assets/11707729/03d74830-7395-44c6-a99f-c542e403238d"></td>
</tr>
<tr>
<td><img width="387" alt="image" src="https://github.com/expo/orbit/assets/11707729/0e440a4e-e9bd-416b-9351-424c819ad253"></td>
<td><img width="397" alt="image" src="https://github.com/expo/orbit/assets/11707729/9dd897b8-caab-4e6d-a …
> [menu-bar] Add PlatformColor support for electron

- CHANGELOG.md
- apps/menu-bar/electron/modules/WindowManager/main.ts
When using titlebarAppearsTransparent the window height does not match the window size on macOS
Add 30px to window height when `titlebarAppearsTransparent = true`
> [menu-bar] Fix Window height on electron

- CHANGELOG.md
- apps/menu-bar/electron/modules/mainRegistry.ts
- apps/menu-bar/modules/file-picker/electron/main.ts
- apps/menu-bar/modules/file-picker/src/FilePickerModule.web.ts
- apps/menu-bar/src/popover/Core.tsx
Closes ENG-11321
Use electron's `dialog` API to add support for the FilePicker module when running electron 
https://github.com/expo/orbit/assets/11707729/8f3be5ec-ddea-4258-89aa-606f2491b986
> [menu-bar] Add Electron support for FilePicker

- CHANGELOG.md
- apps/menu-bar/electron/src/TrayGenerator.ts
When opening a deeplink link on Windows the popover window does not become visible
Update TrayGenerator to automatically open the Popover window when opening a deeplink and auto-hide the window on blur 
https://github.com/expo/orbit/assets/11707729/15ddeb51-ea49-4a6a-82e6-c9eea0a27509
> [menu-bar][electron] Open Popover window when receiving a deeplink

- CHANGELOG.md
- packages/eas-shared/src/download.ts
Closes ENG-11535
Update `downloadAndMaybeExtractAppAsync` to only move the APK file to the final path once the file download is complete 
run `yarn cli download-build https://expo.dev/artifacts/eas/xyz` kill process while downloading or turn off wifi and then rerun `yarn cli download-build https://expo.dev/artifacts/eas/xyz`. It should redownload the APK instead of just returning the corrupted APK path
> [cli] Fix download-build returning cached corrupted APKs

- CHANGELOG.md
- packages/eas-shared/src/run/android/emulator.ts
Recently got a few reports from @brentvatne and @Simek regarding a nonbootable devices being listed in Orbit
AVD IDs cannot contain spaces,  so in order to remove all the extra info returned by `emulator -list-avds`, we can just filter out lines that contain spaces 
Running `yarn cli list-devices -p android` should not list ` INFO    | Storing crashdata in: /tmp/android-brent/emu-crash-34.1.18.db, detection is enabled for process: 92342 (emulator)`
> [cli] Filter extra avd info when listing emulators

- CHANGELOG.md
- packages/eas-shared/src/download.ts
When trying to install an app archive like https://dpq5q02fu5f55.cloudfront.net/Exponent-2.30.10.tar.gz, the installation fails because the extracted contents do not have the .app extension. 
Update `getAppPathAsync` logic to, when extracting an archive and a `.apk`, `.app`or `.ipa` is not found, check if the output dir is an .app but was extracted as folder
Install Expo Go using https://dpq5q02fu5f55.cloudfront.net/Exponent-2.30.10.tar.gz
> [eas-shared] Add support for installing iOS .app files from custom tarballs

- CHANGELOG.md
- apps/cli/src/commands/InstallAndLaunchApp.ts
- packages/eas-shared/src/index.ts
- packages/eas-shared/src/run/index.ts
- packages/eas-shared/src/run/ios/inspectApp.ts
A lot of times users try to install their device builds on simulators and simulator builds on devices via Orbit. Doing so will throw the following error, which is not really descriptive and leads to some confusion 
Update `InstallAndLaunchApp` command to check if the type of app is compatible with the selected device before a trying to install it 
https://github.com/expo/orbit/assets/11707729/9f21adac-28b3-40b6-a565-13cdb5872da2
> [cli] Warn user when trying to an iOS app in a incompatible device

- CHANGELOG.md
- apps/cli/src/commands/ListDevices.ts
While testing the new onboarding flow for expo.dev we noticed that having the physical devices showing up first on the list makes more sense than at the bottom
Update listDevices order to show physical devices first
> [cli] Update listDevices order to show physical devices first

- CHANGELOG.md
- packages/eas-shared/package.json
- packages/eas-shared/src/run/ios/appleDevice/AppleDevice.ts
- packages/eas-shared/src/run/ios/devicectl.ts
- packages/eas-shared/src/utils/fn.ts
- yarn.lock
iPhones connected over WiFi must be unlocked for it to show up on Orbit's list of devices
Update `getConnectedDevicesAsync` function to use Xcode's 15 `devicectl` tool + Usbmuxd to list connected Apple devices improving the reliability of devices connected over Wi-Fi even when the device is locked 
`yarn cli list-devices -p ios`
> [eas-shared] Improve listing connected Apple devices over Wi-Fi

- CHANGELOG.md
- apps/cli/src/commands/DetectIOSAppType.ts
- apps/cli/src/index.ts
- apps/menu-bar/src/commands/detectIOSAppTypeAsync'.ts
- apps/menu-bar/src/popover/Core.tsx
- packages/eas-shared/src/run/ios/appleDevice/installOnDeviceAsync.ts
- packages/eas-shared/src/run/ios/devicectl.ts
When using Orbit for the first time it can be confusing to have to manually select your physical device before trying to launch an IPA. We should instead just automatically select the correct iOS device type depending on the app type
Introduce new `detect-ios-app-type` command 
Run orbit locally:
1. select an iOS simulator
2. launch an internal distribution build 
3. observe the physical device being auto selected
> [menu-bar][cli] Automatically select correct iOS device depending on app type

- CHANGELOG.md
- packages/eas-shared/package.json
- packages/eas-shared/src/fetch.ts
- packages/eas-shared/src/manifest.ts
- yarn.lock
Closes https://github.com/expo/orbit/issues/207
Use `system-ca` to support loading custom CA certificates from the system, by default node will only trust the well-known CAs curated by Mozilla. 
Couldn't repro the exact same issue locally so we still need to validate this fix
> [eas-shared] Add support for self-signed certificates

- apps/cli/pkg.config.json
Follow up of https://github.com/expo/orbit/pull/208
Explicitly add `macos-export-certificate` `.node` files to pkg assets to ensure node bindings work properly when archiving the CLI
yarn `archive` and test the output executable
> [cli] Add macos-export-certificate to pkg assets

- CHANGELOG.md
- apps/menu-bar/modules/menu-bar/ios/MenuBarModule.swift
- apps/menu-bar/modules/rudder/ios/RudderModule.swift
Follow up of https://github.com/expo/orbit/pull/204. Now that `nativeAppVersion` has been removed from Expo constants we need to read it from the Bundle
Update MenuBar module to read app version directly from the Bundle info
Run Menubar locally
> [menu-bar] Fix app version showing undefined

- apps/menu-bar/modules/menu-bar/index.ts
- apps/menu-bar/src/components/DebugLogs/DebugLogRow.tsx
- apps/menu-bar/src/components/DebugLogs/ObjectInspector.tsx
- apps/menu-bar/src/components/DebugLogs/index.tsx
- apps/menu-bar/src/windows/DebugMenu.tsx
- apps/menu-bar/src/windows/Settings.tsx
- apps/menu-bar/src/windows/index.ts
Now that we're promoting the Windows release to a stable version, having a debug menu where we can see the logs of the commands run will help us quickly understand user issues.
Add debug logs to debug menu window
> [menu-bar] Add logs to debug menu

- CHANGELOG.md
- patches/react-native-macos+0.76.0.patch
Closes https://github.com/expo/orbit/issues/224
Patch react-native-macos as suggested by @Saadnajmi to check for `macos` instead of `ios` when creating a `NativeEventEmitter` instance inside `NativeAnimatedHelper`
Run MenuBar locally
> [menu-bar] Fix react-native-macos NativeEventEmitter non-null argument

- CHANGELOG.md
- apps/cli/src/commands/LaunchUpdate.ts
- apps/cli/src/index.ts
- apps/menu-bar/src/commands/launchUpdateAsync.ts
- apps/menu-bar/src/popover/Core.tsx
When users manually set their `runtimeVersion` to something other than `exposdk:x.x.x`, there is no way for us to detect if that app is compatible with Expo Go or not, given that, we should allow user to manually launch updates in Expo Go
Introduce a new `--force-expo-go` flag to launch-update command allowing users to manually specify that their runtime version is compatible with Expo Go
Run MenuBar locally
> Allow users to manually launch updates in Expo Go

- CHANGELOG.md
- apps/menu-bar/electron/forge.config.ts
Closes https://github.com/expo/orbit/issues/223
Add maintainer field to deb packages
Run `yarn make` and install it on Ubuntu
> [menu-bar][electron] Add maintainer field to deb packages

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
- apps/menu-bar/macos/scripts/archive_cli.sh
To prevent the CLI binary from being outdated when archiving the menu-bar, we should add an Xcode build phase to archive the CLI when building in release mode 
Add build phase for archiving and signing the CLI when building the macOS project in Release mode
Archive the macOS app
> [menu-bar][macos] Add CLI archive build phase to macOS project

- CHANGELOG.md
- apps/menu-bar/modules/rudder/electron/main.ts
- apps/menu-bar/modules/rudder/electron/preload.ts
- apps/menu-bar/modules/rudder/src/Rudder.types.ts
- apps/menu-bar/modules/rudder/src/RudderModule.web.ts
RudderStack alreday tracks this when using macOS, we should log the same info for eletron based platforms 
Add `os.arch()` to Rudder module on Electron
Run menu bar locally
> [electron] Add arch info to Rudder module

- CHANGELOG.md
- apps/cli/src/README.md
- packages/eas-shared/src/run/ios/appleDevice/client/UsbmuxdClient.ts
On iOS 18.3 Apple changed the `PairRecordData` response to no longer be an array and directly return an object, resulting in our logic throwing the `TypeError: Cannot read properties of undefined (reading 'HostID')` error when trying to install an app in a locked physical device. 
Update `UsbmuxClient` based on https://github.com/expo/expo/pull/35262
Run CLI locally
> [eas-shared] Ensure UsbmuxClient can load binary plist pair record data from Apple devices

- CHANGELOG.md
- CONTRIBUTING.md
- apps/menu-bar/package.json
- apps/menu-bar/src/components/ProjectIcon.tsx
- apps/menu-bar/src/generated/graphql.possibleTypes.json
- apps/menu-bar/src/generated/graphql.tsx
- apps/menu-bar/src/generated/schema.graphql
- apps/menu-bar/src/graphql/apps.gql
- apps/menu-bar/src/popover/ProjectsSection.tsx
Add support for new project icons, refs:
* https://expo.dev/changelog/website-updates-05-07-2025#account-avatar-and-project-icon-uploads
Update GQL schema, query and logic for determining correct asset, add solid background placeholder for loading images.
Additionally, I have made small tweaks to the CONTRIBUTING guide.
1. Run `cli` locally.
2. Run `menu-bar` locally.
3. Make sure that pinned project icons matches with expo.dev.
> [menu-bar] support displaying new project icons

- CHANGELOG.md
- CONTRIBUTING.md
- apps/menu-bar/macos/scripts/build.sh
- apps/menu-bar/package.json
Now that we have removed the community CLI dependency, we can no longer invoke `react-native run-macos`
Add macos build script
run `yarn macos`
> [menu-bar] Add macos build script

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/AppDelegate.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/AutoResizerRootView.m
- apps/menu-bar/macos/ExpoMenuBar-macOS/ExpoMenuBar-macOS-Bridging-Header.h
- apps/menu-bar/macos/ExpoMenuBar-macOS/PopoverManager.swift
- apps/menu-bar/macos/ExpoMenuBar.xcodeproj/project.pbxproj
We should simplify our AppDelegate logic in order to align it more with Expo's template
Extract the Popover and NSStatusBar item logic into a new class called `PopoverManager`
Run macos menu bar locally
> [menu-bar][macos] Extract Popover logic to a new class

- packages/eas-shared/src/download.ts
Currently the cache checker is not functioning properly, it's returning the directory instead of the cached app file. 
It seems like the defect has been introduced in https://github.com/expo/orbit/pull/256
While trying to install the same APK several times by using the same URL.
I have uploaded an example APK to here: `https://altay.wtf/stuff/example.apk`, you can use it for convenience.
If you run `expo-orbit-cli download https://altay.wtf/stuff/example.apk` twice with the current version, you'll see the CLI returning parent directory path instead of the APK:
```
➜  cli git:(main) ✗ yarn cli download-build https://altay.wtf/stuff/example.apk
'/var/folders/m7/b6d5xtzd7vd0jw4002s1wh_m0000gn/T/expo-orbit-nodejs/downloads-cache/altay.wtf%2Fstuff%2Fexample.apk'
```
and this error in the …
> [eas-shared] fix: update cache check to return app path instead of directory

- CHANGELOG.md
- apps/cli/src/commands/TrustedSources.ts
- apps/cli/src/index.ts
- apps/cli/src/storage.ts
- apps/cli/src/utils.test.ts
- apps/cli/src/utils.ts
- apps/menu-bar/macos/ExpoMenuBar-macOS/PopoverManager.swift
- apps/menu-bar/src/commands/getTrustesSourcesAsync.ts
- apps/menu-bar/src/commands/setTrustedSourcesAsync.ts
- apps/menu-bar/src/popover/Core.tsx
- apps/menu-bar/src/windows/Settings.tsx
- apps/menu-bar/src/windows/index.ts
- packages/common-types/src/InternalError.ts
For security reasons, Orbit should only allow downloading builds from Expo servers by default; if necessary, users can customise trusted sources through the Settings window 
Make `https://expo.dev/**`, `https://staging.expo.dev/**` and `https://expo.test/**` default trusted sources
Run menu bar locally on macOS
> [cli] Add default trusted sources

- CHANGELOG.md
- apps/menu-bar/macos/ExpoMenuBar-macOS/PopoverManager.swift
- apps/menu-bar/src/utils/parseUrl.ts
- apps/menu-bar/src/windows/index.ts
We  deprecated some deeplink formats 17 months ago in https://github.com/expo/orbit/pull/151, and it's time to remove them
Remove deprecated deeplink formats
Run menu bar locally
> [menu-bar] Remove deprecated deeplink formats

- patches/react-native-macos+0.78.3.patch
`react-native-macos` fails to find older versions of Hermes prebuilds because the Maven endpoint it uses does not return all versions. While a new `react-native-macos` version is not released, we need to mually patch this. More context can be found in: https://github.com/microsoft/react-native-macos/issues/2499
Patch `react-native-macos` to find the correct Hermes prebuild based on https://github.com/microsoft/react-native-macos/pull/2505
Run menu-bar locally on macOS
> Patch react-native-macos to find correct Hermes prebuild
